dist: xenial
sudo: required

language: node_js
node_js:
- "8.11.3"

before_install:
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get update -qq

install:
- sudo apt-get install -qq g++-8
- sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 90
- git clone https://github.com/devosoft/Empirical ../Empirical
- git clone https://github.com/emscripten-core/emsdk.git && cd emsdk && git pull && ./emsdk install latest && ./emsdk activate latest && . ./emsdk_env.sh && cd ..

script:
- make test

after_success:
- git config --global user.email "travis@travis-ci.org"
- git config --global user.name "Travis CI"
- cd web
- git init
- git remote add origin https://${GH_TOKEN}@github.com/devosoft/evoke.git > /dev/null 2>&1
- git checkout -b gh-pages
- git add .
- git commit --message "Travis build ${TRAVIS_BUILD_NUMBER}"
- test ${TRAVIS_BRANCH} = "master" && git push --force --quiet origin gh-pages

env:
  global:
    secure: xMFozZeYtskLNWxOLciwp7lxfBI4fBpatXYVIPYZqPszjSxH0E6cdTeGq++qW5nlbpn498wIY17byl+exkvZjt9LllmIJr/i3r7VrdBx5rCgRlf1zkgJ1DVHfu6pmS5Pp2e/X3Gg9lQgWoCdCyve/C8bKhuZ7xAPO8R40MlDOgtL8A9oNyq+MrTI4rfIDHGDBdnQA+EqgKGkUPuEu8qtffU/R7Th6YCQQLq17eItvbFrGU5zi6c3x4eqcyeIYsDLnhLq4Y2uxuJMOZwJCRmfxpYCBYBouw80A9nCwjcgvaI9QVLkJcK2v8G62CcGSs7qAwSQVnJQl9LWXNxKVTOSsL4N7/S1eNuLqcZUbytFXKuISEoJkXjTjZK2vkvgdfjfMPJkXN5OB8AqRmauTPyHboVvia3vL9BTTwWJT/fTlWHem1qZCy/npgcWcuDbCCz96zBn6sRFI0vZqqTJShUJ7HbDyXiuD0e83dMwBpEMev++pRsk1MWmJstXKikDlA6ZAFYx/rs0wsNbgwtDw01U30PQNUa6SJKuKp9y92gorSk9wvO30BMUfKsjINQEBTMwAufIS9VYCghIAqMXPy/+POpnvZ1C6X9W+e506dVugLPUyO4mTc5hjvKjDa/hmKwi5l7XQA18zoXLrcf8016973Z+zCzxasrWiZPo7kJWVpY=
